# Change these first
owner: Timberix # Your GitHub organization or username, where this repository lives
repo: status.timberix.toys # The name of this repository

sites:
  - name: Website
    url: https://timberix.toys

status-website:
  theme: light
  cname: status.timberix.toys
  logoUrl: https://timberix.toys/wp-content/uploads/2024/01/timberix-logo.svg
  name: TIMBERIX Status
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://timberix.toys

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
